#!/usr/bin/env bash

COMMAND=$1
airpods_status=$(bluetoothctl devices Connected 2> /dev/null | grep -c "AirPods")

LABEL="Airpods"

if [ "$airpods_status" = "0" ]; then
    CLASS="disconnected"
else
    CLASS="connected"
fi

if [ "$COMMAND" = "toggle" ]; then
    if [ "$airpods_status" = "0" ]; then
        bluetoothctl devices | grep AirPods | awk '{print $2}' | xargs bluetoothctl connect
    else
        bluetoothctl devices | grep AirPods | awk '{print $2}' | xargs bluetoothctl disconnect
    fi
elif [ "$COMMAND" = "icon" ]; then
    if [ "$airpods_status" = "0" ]; then
        LABEL="󰟎" # Disconnected
    else
        LABEL="󰥰" # Connected
    fi
fi

echo "{\"text\":\"$LABEL\",\"class\":\"$CLASS\"}"
